return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "lua",
      "htmldjango",
      "html",
      "dockerfile",
      "gitcommit",
      "git_rebase",
      "gitignore",
      "cpp",
      "css",
      "graphql",
      "pug",
      "smali",
      "swift",
      "bash",
      "python",
      "toml",
      "javascript",
      "typescript",
      "tsx",
      "json",
      "jsonc",
      "php",
    },
  },
}
